### ISSUE TITLE
the time when tweet was created is wrong

### ISSUE THREAD

**Issue by scotthou94** [GetStream/django_twitter#19] opened 2016-10-26 03:25 UTC
I have `{{ activity.time|timesince }} ago` for showing the time at which the tweet was created. However, it seems like it is 8 hours before the actual time. When I post a new tweet, it shows that the tweet was created 8 hours ago.
I changed the timezone to my local timezone in the settings.py but the problem is still there. I wonder how  can I fix this. Hope you can help me with this. Thanks in advance.

**Comment by JelteF** [comment] 2016-10-26 12:05
What timezone are you in? Is it 8 hours before, or after UTC? It could be that it is either not correcting at all or that is correcting twice.

**Comment by tbarbugli** [comment] 2016-10-26 12:07
when you read feeds, activity.time is always in UTC. You need to convert that to your local time, Django has nice helper functions to do that. @JelteF can you add a link about this to the conversation and perhaps mention this in the django lib?

**Comment by JelteF** [comment] 2016-10-26 12:11
This example app has a `time_difference` filter that can probably be used here. https://github.com/GetStream/django_twitter/blob/8e5a3ddf1f78bbe2ff2a13b0b08c5ab82021a661/stream_twitter/templatetags/filters.py#L10

**Comment by scotthou94** [comment] 2016-10-26 12:33
I'm in China so that's 8 hours after utc.
I try to use this `time_difference` filter, but it just shows the actual time the tweet is created so I suppose there's an exception in this part of the code
```python
def time_difference(value):
    now = datetime.utcnow().replace(tzinfo=utc)
    try:
        difference = now - value
```
but I'm not sure what went wrong

**Comment by dwightgunning** [comment] 2017-10-05 15:42
Apologies @scotthou94 that this one slipped.

I've just had a closer look and from what I can see, everything is working by design. Times are stored and processed as UTC. The relative 'time_difference' function works as both timestamps going into the time arithmetic calculation are timezone aware.

I'll close this out for now. If you'd like to re-open and get some more support on this just let me know.

**Closed by dwightgunning** 2017-10-05 15:42 UTC
